### PR TITLE
Fix recording to wait out initial silence

### PR DESCRIPTION
**Pull request by ritamsarmah**

### CODE REVIEW

**Comment by nkansal96** [comment]
Sorry, I'm not that familiar with Ruby. Can you briefly explain how `self.wait_on_silence` works? Specifically, what is the maximum size of the silence buffer returned? For the Python and Go SDKs, its keeps up to 1.25s worth of buffer before beginning the actual recording. 

- What's the relationship between `BYTES_PER_BLOCK` and `FRAMES_PER_BUFFER`? How do you define a "block", "buffer", and "frame"?
- What is the significance of the `padding_size` variable and what is the `0.1` constant?
- What are you checking for in this condition: `buffer.size > 8 * padding_size`
- How many bytes are you removing with the `buffer = buffer[padding_size..buffer.size]` line? What maximum size of the buffer does this result in?

**Comment by ritamsarmah** [comment]
The function basically has a "fixed-size" buffer and appends new data from the input device to the buffer. If non-silent audio is detected, it will pass back that buffer with the initial detected sound along with a specified amount of earlier samples (padding) to ensure the audio isn't clipped too much.

- Many of the naming conventions were taken from the [PortAudio examples](http://portaudio.com/docs/v19-doxydocs/paex__read__write__wire_8c_source.html) in their documentation. Admittedly, my experience with audio terminology is limited, so I'll do my best to accurately clarify:
  - The `sample_block` is written to by PortAudio for every call to `ReadStream()` and has a size determined by our WAV file format. The `buffer` is a sequence of multiple sample blocks.
  - `FRAMES_PER_BUFFER`: the number of sample frames that PortAudio will request from the input device.
  - `BYTES_PER_BLOCK`: number of bytes per "block" (a.k.a. `sample_block`) of audio read in by PortAudio in each call to `ReadStream()`. This is equal to `FRAMES_PER_BUFFER * NUM_CHANNELS * SAMPLE_SIZE`.
- `padding_size` refers to a number of blocks. The formula was taken from PortAudio example code to convert from duration in time (in this case 0.1 seconds).
- Basically checks if the buffer exceeds 0.8s worth of sound (in effect a maximum length for buffer, though it is vague as written)
- `padding_size..buffer.size` is a range. The line removes the first 0.1 s of sound in the buffer and keeps the rest.

Admittedly, the solution definitely might need some additional testing and tweaking for readability, due to being written in a bit of rush. But I tested it to the best of my abilities in multiple situations (as well as trying different constants in place of 0.1 and 8) and this solution seems to perform well in minimizing silence without clipping audio.

As a side note, I was testing the behavior of the Python SDK listening function, and I could often create situations where it would cut off too much audio (unless I'm misusing the listen function--I tested using `listen(length=3)`. I included an example in a ZIP file for reference.

[test.wav.zip](https://github.com/nkansal96/aurora-ruby/files/2083165/test.wav.zip)

**Comment by nkansal96** [comment]
I see now. If you have time to increase its readability that would be great. Formal testing might not be required, but just make sure that it works as intended.

I am however curious how the audio was clipped in the sample you generated. Which version of the SDK did you use and how were you able to produce it? I haven't come across this and the whole point of keeping a buffer prior to the actual speaking was to not have this clipping.

**Comment by ritamsarmah** [comment]
v0.1.2 in Python 3.6.4. Testing process involved calling `listen(length=3)`, waiting a few seconds, and speaking. Speech with distinct "quick" consonants at the beginning of words, such as 'test', makes the clipping clearer (though in most other cases the clipping is subtle or non-existent). I couldn't really identify the logical cause.

**Comment by nkansal96** [comment]
Ok, I'll look into it. In the meanwhile, lets change it to be 1.25s to be consistent with the other SDKs and this looks find.

**Pull request merged**
